[project]
name = "model-conversion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "alokchoudharyguliya", email = "waynerooney0089@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "coremltools>=9.0",
    "onnx>=1.23.1",
    "onnxconverter-common>=1.16.0",
    "onnxruntime>=1.24.3",
    "onnxscript>=0.7.2",
    "psutil>=7.2.2",
    "python-dotenv>=1.2.4",
    "tensorflow>=2.21.0",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
]

[project.scripts]
model-conversion = "model_conversion:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
